### PR TITLE
Add configuration section

### PR DESCRIPTION
**Pull request by rdev5**

### CODE REVIEW

**Comment by mmoayyed** [comment]
I personally am not in favor of duplicating settings and "polluting" the configuration. Majority of deployments do not need the authz rules. Keep only what you need; link to relevant sections in the docs.

**Comment by rdev5** [comment]
I'm not a fan of duplicating settings either, though some of those guidelines should probably be reiterated for `management.properties` in this project's README.

Having said that, my intentions were to **move** these settings to the actual app they pertain to (CAS Management Webapp) and link to it from the [CAS Properties](https://apereo.github.io/cas/5.1.x/installation/Configuration-Properties.html#management-webapp) documentation, but I didn't want to propose these changes if there was nothing to link to (i.e. this PR hadn't been merged yet).

**Comment by mmoayyed** [comment]
Gotcha. Yes, guidelines for certain. Settings, less so. 

And I must apologize because I don't quite follow what you're saying; where was nothing to link to? 

The documentation for the webapp links to the relevant section of the properties, right? See "To see the relevant list of CAS properties, please review this guide.".
https://apereo.github.io/cas/5.1.x/installation/Installing-ServicesMgmt-Webapp.html

Right below it, there is a section for LDAP authz with yet another link (This might might need correcting a bit to point to the specific section)

So I recommend that you add all the guidelines you need to the official docs; get any and all PRs merged. Then come back here and update the README with links to the new-found settings and pages.

Make sense, or am I off?

**Comment by rdev5** [comment]
More or less. Let's back up for a minute to the referenced [CAS Management Webapp guide](https://apereo.github.io/cas/5.1.x/installation/Installing-ServicesMgmt-Webapp.html).

The opening line says:

> The services management webapp **is no longer part of the CAS server** and is a standalone web application.

It stands to reason that the configuration settings for this *standalone application* should NOT be "polluting" the CAS server configuration as presently implied by virtue of listing them as *part of* the CAS server configuration here: https://apereo.github.io/cas/5.1.x/installation/Configuration-Properties.html#management-webapp

What I'm proposing is that we completely remove the [Management Webapp section](https://apereo.github.io/cas/5.1.x/installation/Configuration-Properties.html#management-webapp) (and by extension its [LDAP Authorization subsection](https://apereo.github.io/cas/5.1.x/installation/Configuration-Properties.html#ldap-authorization)) and move them to this project which is what this PR is for.

If/when this PR gets merged, we would then have a section available ([example](https://github.com/rdev5/cas-services-management-overlay/blob/ac3c9db7cc5f20ee6b1d176dbc79c4b3c2e9922e/README.md#configuration-managementproperties)) to link from the referenced *CAS Management Webapp guide* whereas in the [current README.md](https://github.com/apereo/cas-services-management-overlay#cas-services-management-overlay) (master branch) this section does not exist.

**Comment by mmoayyed** [comment]
> The services management webapp is no longer part of the CAS server and is a standalone web application.

Correct. It should however say, "no longer part of the CAS Server **web application**". Otherwise this is all CAS and that's where all/most CAS documentation lives.

> as presently implied by virtue of listing them as part of the CAS server configuration here: 

Given the link clearly says, "this section applies to the management web application", I dont quite understand the confusion point, but never mind that. 

> What I'm proposing is that we completely remove the Management Webapp section (and by extension its LDAP Authorization subsection) and move them to this project which is what this PR is for.

Gotcha. Negative.

If any of those settings every change or removed, one has to do double duty to make the code in one place, update the overlay in some place else. If and when there is a gradle overlay for the app (and there is in many deployments) that would be triple duty.

**Comment by mmoayyed** [comment]
Again, all you need in the overlay (I would suggest) is the following:

# Configuration

The management web application is controlled by the management.properties file, whose contents may be controlled via the following settings:
https://apereo.github.io/cas/5.1.x/installation/Configuration-Properties.html#management-webapp

The entry to the application may also be handled via various authz rules, described here:
https://apereo.github.io/cas/5.1.x/installation/Installing-ServicesMgmt-Webapp.html

LDAP authorization that controls access to the app is documented here:
https://apereo.github.io/cas/5.1.x/installation/Installing-ServicesMgmt-Webapp.html#ldap

You may not need this.

LDAP authorization settings are documented and controlled via here:
https://apereo.github.io/cas/5.1.x/installation/Configuration-Properties.html#ldap-authorization

Which again, you need to put inside the management.properties file.

**Comment by rdev5** [comment]
> Correct. It should however say, "no longer part of the CAS Server web application". Otherwise this is all CAS and that's where all/most CAS documentation lives.

I understand that `https://apereo.github.io/cas` is where most or all of CAS documentation lives and I don't really have a problem with that. However, I think that's only one way to look at it, but certainly not the only one.

What I'm not sure I agree with, else don't understand, is this: should this same "centralization of documentation approach" be assumed of the [CAS Properties](https://apereo.github.io/cas/5.1.x/installation/Configuration-Properties.html) page?

In other words, if you're starting with the *CAS Properties* page, using it as a Configuration Reference, for example, 100% of the settings listed are intended for `cas.properties` such that the settings `cas.mgmt.userPropertiesFile` and `cas.ticket.tgt.maxLength` are *presented* adjacent to each other, defined in the **same file** just you would define `cas.ticket.tgt.maxLength` and `cas.ticket.tgt.onlyTrackMostRecentSession` adjacent to each other. As you've already pointed out, the management application would not be controlled by this file and therefore not pick up these changes.

Another simple solution would be to just simply add another documentation page for this (i.e. /installation/Management-Properties.html) and move them there instead.

**Comment by mmoayyed** [comment]
> What I'm not sure I agree with, else don't understand, is this: should this same "centralization of documentation approach" be assumed of the CAS Properties page?

That's an excellent question; let me expand on that a little bit (and some of this is me thinking out loud): When "we" set out to reorganize docs with v5 and such, our line of thinking was "one page for everything". Much of that model was inspired by evaluating other open source projects (particularly in the Spring framework family) trying to learn what might or might not work. Note that I am not saying this was done correctly; only that the motivation was inspired by: "Keep everything in one place; easier to find, easier to build, easier to update, easier to explain". We did think about moving much of the documentation to specific pages next to each feature page or as you say, portions to the overlays. In the end, it all proved to be more annoying than anything else. Of course, no matter what you and I do, there will always be room for more improvement. Maybe all of that in some needs to be thought about and reorganized yet again; the problem is simply bandwidth and impatience.

So that is a long way of saying, I sure understand that when you start with "CAS Properties" you have a tendency to think "CAS server web application: the core thingy" properties and all else is auxiliary and that the management web application has its own personality, etc. Sure. Maybe. On the other hand, there are about 7-8 other "web applications" also produced by CAS, some contain the core engine, some contain other servers of which CAS is a client and they are listed also in the central place. It's a phone book. Deviating from that approach as I indicated would not only increase maintenance efforts *for all of us*, but it would mean that we'd have to do the same thing for all other auxiliary web applications that we do or may produce in the future. Which means you need to move settings from the central docs to "their overlays" too.

> Another simple solution would be to just simply add another documentation page for this (i.e. /installation/Management-Properties.html) and move them there instead in which case, this PR should just be closed/declined/modified with your suggestions.

I would find this option more reasonable. I hesitate a bit because I imagine at some point someone would come along and say "If this is a place where CAS settings are, how come there is this other page then? and how many pages are there? Cant I just go to the phone book and search for something?". 

This also would cause in one particular area: we have often talking about internally whether we should dynamically build the central properties page to explain each and every single field (because there is now comprehensive documentation for each field in form of javadocs and there is a shell that is able to produce documentation for you from CLI or REST). We have thought about redesigning that page only, dynamically, so it auto updates every time we add a new field, and it auto presents the documentation for each field in decent form along with examples and default values as well as any additional notes we might want to add.

Which means, breaking the page into a second page or more would prevent us from doing that in one shot to some degree. But then again, maybe not.

Let me think about this. I very much appreciate your time and patience. Thank you. I'll get back to you.

**Comment by rdev5** [comment]
I think I understand a little better the rationale behind this "phone book" approach and the context in which it would be preferred. Albeit, it is a little *monolithic* in nature which is a pattern I've grown disenchanted with over the past couple years in my line of work.

At this point, I think I'd propose one or two changes yet to the current *CAS Properties* page that may accommodate both use cases and possibly future plans to auto-update this singular page.

First, note the way sections are currently outlined:
````
# Title (i.e. *CAS Properties*)
## Topic (i.e. *Embedded Container*)
### Subtopic (i.e. *Embedded Tomcat Container*)
#### ...
````
This puts *Embedded Container* at the same level (h2) as *Management Webapp*.

Now consider the following revised structure:
````
# Title (i.e. *CAS Properties*)
## Application (i.e. *CAS Server Web Application*, )
### Topic (i.e. *Embedded Container*)
#### Subtopic (i.e. *Embedded Tomcat Container*)
##### ...
````
This would put *CAS Server Web Application* at the same level as *Management Webapp*. You still return the same singular "phone book" documentation page (URL) but now we're executing context a little better.

My second suggestion: https://github.com/apereo/cas/pull/2926

**Comment by mmoayyed** [comment]
> This would put CAS Server Web Application at the same level as Management Webapp. You still retain the same singular "phone book" documentation page (URL) but now we're executing context a little better.

Perfectly good. Sure. 

You'll just need to account for two things:

1. Because there is more than one thing that ships with an embedded server, and because there is more than one embedded server your changes need to account for all areas. Don't worry if you miss a few; I'll point them out.
2. Changes need to be applied to master as well, in case you were thinking of 5.1.

**Comment by rdev5** [comment]
Works for me. Now, if I can just find the time to do all this... :)

**Comment by mmoayyed** [comment]
Sweet. I'll get the pull closed for now; Keep the PRs coming and we'll merge as quickly as possible. Thanks again!

**Comment by mmoayyed** [comment]
@rdev5 you might find this interesting for your needs: https://apereo.github.io/2017/10/13/520rc4-release/#configuration-metadata-ui

**Pull request closed without merging**
